[package]
name = "stelo_extractor"
version = "0.2.0"
edition = "2021"

[dependencies]
quick-xml = "0.28"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
chrono-tz = "0.8"
clap = { version = "3.2", features = ["derive", "color"] }
